name: islami
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  build_runner: ^2.12.0
  flutter_gen: ^5.14.1
  flutter_svg: ^2.3.0
  flutter_bounceable: ^1.2.0
  flutter_native_splash: ^2.4.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_gen:
  output: lib/core/gen/ 

  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/files/quran/
  fonts:
    - family: Janna LT
      fonts:
        - asset: assets/fonts/Janna LT Regular.ttf
        - asset: assets/fonts/Janna LT Bold.ttf